name: CI-CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven (backend/app)
        run: mvn -B clean package
        working-directory: backend/app

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: backend/app/target/*.jar
